HAI 1.2
  I HAS A LINEZ ITZ 0
  I HAS A I ITZ 0
  VISIBLE "HOU MUCH LINEZ"
  GIMMEH LINEZ
  LINEZ R MAEK LINEZ A NUMBR
  I R MAEK I A NUMBR
  VISIBLE ""

  IM IN YR LOOP UPPIN YR I TIL BOTH SAEM I AN LINEZ
    I HAS A J ITZ 0
    IM IN YR LOOP UPPIN YR J TIL BOTH SAEM J AN SUM OF I AN 1
        VISIBLE "*"!
    IM OUTTA YR LOOP
    VISIBLE ""
  IM OUTTA YR LOOP


KTHXBYE
